name: Deploy WordPress Theme

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Hostinger
      run: rsync -av --exclude='/.git*' --delete ./ /files/public_html/terryjudemiller/wp-content/themes/tjm-2023-redesign
      
      env:
        SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
